export type Category = {
  id: string;
  name: string;
  emoji: string;
  words: { word: string; hint: string }[];
};

export const wordCategories: Category[] = [
 {
  id: "malayalam-movies",
  name: "Malayalam Movies",
  emoji: "🎬",
  words: [
    { word: "Kumbalangi Nights", hint: "Family Drama" },
    { word: "Lucifer", hint: "Political Thriller" },
    { word: "Premam", hint: "Romance" },
    { word: "Manichitrathazhu", hint: "Psychological Horror" },
    { word: "Drishyam", hint: "Investigation" },
    { word: "Bangalore Days", hint: "Friendship" },
    { word: "Ustad Hotel", hint: "Cooking" },
    { word: "Spadikam", hint: "Father Son" },
    { word: "Charlie", hint: "Free Spirit" },
    { word: "Maheshinte Prathikaram", hint: "Revenge" },
    { word: "Take Off", hint: "Rescue Mission" },
    { word: "Uyare", hint: "Acid Attack Survivor" },
    { word: "Virus", hint: "Nipah Outbreak" },
    { word: "Ayyappanum Koshiyum", hint: "Ego Clash" },
    { word: "Jallikattu", hint: "Buffalo Chaos" },
    { word: "Joji", hint: "Macbeth Inspired" },
    { word: "Android Kunjappan", hint: "Robot Grandpa" },
    { word: "Home", hint: "Family Technology Gap" },
    { word: "Minnal Murali", hint: "Superhero" },
    { word: "Thondimuthalum Driksakshiyum", hint: "Police Case" },
    { word: "Salt N Pepper", hint: "Food Romance" },
    { word: "Action Hero Biju", hint: "Police Stories" },
    { word: "Jacobinte Swargarajyam", hint: "Family Abroad" },
    { word: "Ennu Ninte Moideen", hint: "True Love Story" },
    { word: "Classmates", hint: "College Reunion" },
    { word: "Traffic", hint: "Hyperlink Thriller" },
    { word: "Memories", hint: "Serial Killer" },
    { word: "Mumbai Police", hint: "Twist Ending" },
    { word: "Anjaam Pathiraa", hint: "Criminologist" },
    { word: "Forensic", hint: "Crime Investigation" },
    { word: "The Great Indian Kitchen", hint: "Patriarchy" },
    { word: "Hridayam", hint: "College Life" },
    { word: "Varane Avashyamund", hint: "Marriage Proposal" },
    { word: "Kurup", hint: "Fugitive" },
    { word: "Driving Licence", hint: "Actor vs Fan" },
    { word: "Ishq", hint: "Moral Policing" },
    { word: "Love Action Drama", hint: "Romantic Comedy" },
    { word: "Oru Vadakkan Selfie", hint: "Social Media" },
    { word: "Neelakasham Pachakadal Chuvanna Bhoomi", hint: "Bike Trip" },
    { word: "Mayaanadhi", hint: "Tragic Romance" },
    { word: "Rorschach", hint: "Mystery Revenge" },
    { word: "Bheeshma Parvam", hint: "Gangster Family" },
    { word: "CBI 5", hint: "Investigation Series" },
    { word: "Nayattu", hint: "Police Run" },
    { word: "Kappela", hint: "Phone Love" },
    { word: "Thinkalazhcha Nishchayam", hint: "Wedding Chaos" },
    { word: "Sudani from Nigeria", hint: "Football Player" },
    { word: "Ee Ma Yau", hint: "Funeral Drama" },
    { word: "Amen", hint: "Church Story" },
    { word: "North 24 Kaatham", hint: "Journey" },
    { word: "22 Female Kottayam", hint: "Revenge Story" },
    { word: "Diamond Necklace", hint: "Gulf Life" },
    { word: "Cocktail", hint: "Thriller" },
    { word: "Ayalum Njanum Thammil", hint: "Doctor Life" },
    { word: "Puthiya Niyamam", hint: "Justice" },
    { word: "Kali", hint: "Anger Issues" },
    { word: "Solo", hint: "Four Stories" },
    { word: "CIA Comrade in America", hint: "Love Journey" },
    { word: "Godha", hint: "Wrestling" },
    { word: "Rakshadhikari Baiju", hint: "Local Hero" },
    { word: "Kunjiramayanam", hint: "Village Comedy" },
    { word: "Adi Kapyare Kootamani", hint: "Hostel Comedy" },
    { word: "Two Countries", hint: "Marriage Comedy" },
    { word: "Meesa Madhavan", hint: "Thief Hero" },
    { word: "Kilukkam", hint: "Comedy Classic" },
    { word: "Chandralekha", hint: "Romantic Comedy" },
    { word: "Godfather", hint: "Family Rivalry" },
    { word: "In Harihar Nagar", hint: "Friends Comedy" },
    { word: "Ramji Rao Speaking", hint: "Comedy Thriller" },
    { word: "Punjabi House", hint: "Debt Comedy" },
    { word: "Thenmavin Kombath", hint: "Love Story" },
    { word: "Nadodikkattu", hint: "Gulf Dream" },
    { word: "Devasuram", hint: "Feudal Lord" },
    { word: "Vanaprastham", hint: "Kathakali Artist" },
    { word: "Peranbu", hint: "Father Daughter" },
    { word: "Thanmathra", hint: "Memory Loss" },
    { word: "Bhramaram", hint: "Revenge" },
    { word: "Oppam", hint: "Blind Man" },
    { word: "Pulimurugan", hint: "Tiger Hunter" },
    { word: "Big B", hint: "Gangster" },
    { word: "Black", hint: "Kidnap Thriller" },
    { word: "Runway", hint: "Smuggling" },
    { word: "Rajamanikyam", hint: "Business Tycoon" },
    { word: "Kasaba", hint: "Police Story" },
    { word: "Masterpiece", hint: "Campus Thriller" },
    { word: "Abrahaminte Santhathikal", hint: "Police Brothers" },
    { word: "The Priest", hint: "Supernatural Crime" },
    { word: "Cold Case", hint: "Mystery Investigation" },
    { word: "Night Drive", hint: "Road Thriller" },
    { word: "Malik", hint: "Coastal Leader" },
    { word: "Pathemari", hint: "Gulf Migration" },
    { word: "Kayamkulam Kochunni", hint: "Robin Hood" },
    { word: "Marakkar", hint: "Naval Warrior" },
    { word: "1971 Beyond Borders", hint: "War" },
    { word: "Keerthi Chakra", hint: "Army Life" },
    { word: "Kuruthi", hint: "Religious Conflict" },
    { word: "Pada", hint: "Hostage Drama" },
    { word: "Jana Gana Mana", hint: "Courtroom Thriller" }
  ]
},
  {
    id: "kerala-places",
    name: "Kerala Places",
    emoji: "🌴",
    words: [
      { word: "Munnar", hint: "Hill Station" },
      { word: "Alappuzha", hint: "Backwaters" },
      { word: "Kochi", hint: "Port City" },
      { word: "Wayanad", hint: "Forests" },
      { word: "Thiruvananthapuram", hint: "Capital" },
      { word: "Kovalam", hint: "Beach" },
      { word: "Thekkady", hint: "Wildlife" },
      { word: "Guruvayur", hint: "Temple Town" },
      { word: "Kasargod", hint: "Northern Tip" },
      { word: "Varkala", hint: "Cliff Beach" },
    ],
  },
  {
  id: "malayalam-food",
  name: "Malayalam Food",
  emoji: "🍛",
  words: [
    { word: "Puttu", hint: "Steamed Breakfast" },
    { word: "Appam", hint: "Lacy Pancake" },
    { word: "Sadya", hint: "Banana Leaf Feast" },
    { word: "Kappa Biriyani", hint: "Tapioca Dish" },
    { word: "Karimeen Pollichathu", hint: "Wrapped Fish" },
    { word: "Pazham Pori", hint: "Sweet Snack" },
    { word: "Avial", hint: "Mixed Vegetables" },
    { word: "Idiyappam", hint: "String Hoppers" },
    { word: "Erissery", hint: "Pumpkin Curry" },
    { word: "Payasam", hint: "Sweet Dessert" },

    { word: "Dosa", hint: "Crispy Crepe" },
    { word: "Idli", hint: "Steamed Rice Cake" },
    { word: "Sambar", hint: "Lentil Curry" },
    { word: "Rasam", hint: "Spicy Soup" },
    { word: "Parotta", hint: "Layered Flatbread" },
    { word: "Beef Fry", hint: "Spicy Meat Dish" },
    { word: "Fish Curry", hint: "Tangy Curry" },
    { word: "Chicken Roast", hint: "Dry Spicy Chicken" },
    { word: "Egg Roast", hint: "Egg Masala" },
    { word: "Kappa", hint: "Boiled Tapioca" },

    { word: "Kanji", hint: "Rice Porridge" },
    { word: "Chammandi", hint: "Coconut Chutney" },
    { word: "Thoran", hint: "Dry Veg Stir Fry" },
    { word: "Olan", hint: "Coconut Milk Curry" },
    { word: "Kaalan", hint: "Yogurt Curry" },
    { word: "Pulissery", hint: "Sour Curry" },
    { word: "Inji Curry", hint: "Ginger Dish" },
    { word: "Pachadi", hint: "Sweet Sour Curry" },
    { word: "Kichadi", hint: "Yogurt Veg Dish" },
    { word: "Sambar Sadam", hint: "Rice Mix" },

    { word: "Chicken Biriyani", hint: "Festive Rice Dish" },
    { word: "Mutton Biriyani", hint: "Spicy Rice Dish" },
    { word: "Malabar Parotta", hint: "Kerala Bread" },
    { word: "Pathiri", hint: "Rice Flatbread" },
    { word: "Unnakaya", hint: "Sweet Banana Roll" },
    { word: "Kozhukatta", hint: "Rice Dumpling" },
    { word: "Ada Pradhaman", hint: "Rice Dessert" },
    { word: "Palada Payasam", hint: "Milk Dessert" },
    { word: "Chakka Varatti", hint: "Jackfruit Jam" },
    { word: "Chakka Puzhukku", hint: "Jackfruit Dish" },

    { word: "Meen Fry", hint: "Fried Fish" },
    { word: "Chemmeen Curry", hint: "Prawn Curry" },
    { word: "Njandu Curry", hint: "Crab Curry" },
    { word: "Beef Curry", hint: "Meat Gravy" },
    { word: "Duck Roast", hint: "Spicy Duck Dish" },
    { word: "Kozhi Curry", hint: "Chicken Curry" },
    { word: "Mutta Curry", hint: "Egg Curry" },
    { word: "Vegetable Stew", hint: "Mild Curry" },
    { word: "Appam Stew", hint: "Combo Dish" },
    { word: "Banana Chips", hint: "Crunchy Snack" }
  ]
},
  {
    id: "world-celebs",
    name: "Famous People",
    emoji: "⭐",
    words: [
      { word: "Mohanlal", hint: "Malayalam Actor" },
      { word: "Mammootty", hint: "Malayalam Actor" },
      { word: "Sachin Tendulkar", hint: "Cricketer" },
      { word: "A.R. Rahman", hint: "Music Composer" },
      { word: "Elon Musk", hint: "Tech Billionaire" },
      { word: "Lionel Messi", hint: "Footballer" },
      { word: "Virat Kohli", hint: "Cricketer" },
    ],
  },
];
